import { CMSPage } from "./types";

export const INITIAL_CMS_PAGES: CMSPage[] = [
  {
    id: 12,
    title: "Cookie Policy",
    language: "English",
    location: "Footer Bottom",
    isVisible: true,
    pageType: "Custom",
    date: "2026-07-28 / 13:29",
  },
  {
    id: 11,
    title: "Privacy Policy",
    language: "English",
    location: "Footer Bottom",
    isVisible: true,
    pageType: "Custom",
    date: "2026-07-28 / 13:29",
  },
  {
    id: 10,
    title: "Sell on Modesy",
    language: "English",
    location: "Top Menu",
    isVisible: true,
    pageType: "Custom",
    date: "2026-07-28 / 13:28",
  },
  {
    id: 9,
    title: "About Us",
    language: "English",
    location: "Information",
    isVisible: true,
    pageType: "Custom",
    date: "2026-07-28 / 13:28",
  },
  {
    id: 8,
    title: "محلات",
    language: "Arabic",
    location: "Quick Links",
    isVisible: true,
    pageType: "Default",
    date: "2026-07-27 / 15:27",
  },
  {
    id: 7,
    title: "مدونة",
    language: "Arabic",
    location: "Quick Links",
    isVisible: true,
    pageType: "Default",
    date: "2026-07-27 / 15:27",
  },
  {
    id: 6,
    title: "اتصال",
    language: "Arabic",
    location: "Top Menu",
    isVisible: true,
    pageType: "Default",
    date: "2026-07-27 / 15:27",
  },
  {
    id: 5,
    title: "البنود و الظروف",
    language: "Arabic",
    location: "Information",
    isVisible: true,
    pageType: "Default",
    date: "2026-07-27 / 15:27",
  },
  {
    id: 4,
    title: "Shops",
    language: "English",
    location: "Quick Links",
    isVisible: true,
    pageType: "Default",
    date: "2026-07-24 / 07:40",
  },
  {
    id: 3,
    title: "Blog",
    language: "English",
    location: "Quick Links",
    isVisible: true,
    pageType: "Default",
    date: "2026-07-24 / 07:40",
  },
  {
    id: 2,
    title: "Contact",
    language: "English",
    location: "Top Menu",
    isVisible: true,
    pageType: "Default",
    date: "2026-07-24 / 07:40",
  },
  {
    id: 1,
    title: "Terms & Conditions",
    language: "English",
    location: "Information",
    isVisible: true,
    pageType: "Default",
    date: "2026-07-24 / 07:40",
  },
];
